---
name: rule2run-echo
description: "Launches an action to echo phrase of the day"
enabled: false

trigger:
  description: "Triggers on specified intervals"
  type: core.st2.IntervalTimer
  parameters:
    unit: "seconds"
    delta: 15

action:
  ref: st2webhook_test.action_echo
  description: "Use the defined action to echo the phrase"
